# NICE OLED Config
## Set to n to disable slave animation
CONFIG_NICE_OLED_GEM_ANIMATION=y
## 2x slower, 30fps
CONFIG_NICE_OLED_GEM_ANIMATION_MS=1920

## set max to 150
CONFIG_NICE_OLED_GEM_WPM_FIXED_RANGE_MAX=150

## LUNA
CONFIG_NICE_OLED_WIDGET_WPM=n
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=n
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_LUNA=n
